---
title: "NBA Simulator"
author: "Alberto Sanchez Rodelgo"
date: "8/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Motivation and brief description

The objective of this project is to be able to simulate a complete NBA season as accurately as possible. The main driver behind the simulation engine are offensive and defensive power rankings of the teams. 

Team Power Rankings are computed from players' directly observable statistics: points, rebounds, free throws, assists, steals, etc. Box plus minus are not considered as they concern mainly to individual performances and are implicitly included in the offensive and defensive team performaces.

Players' stats are predicted based on their stats from previous seasons combined with historical data for similar players at the age they enter the current season. This allows for corrections when there may be declining/improving stats by age, or when there is lack of consistent historical stats. 
Rookies stats are estimated from College stats adjusted to NBA minutes of play. Non-college rookies stats are estimated from their respective leagues stats (if existing, case of main European leagues or Euroleague). Everybody else's stats are estimated based on an average player performace according to historical data for players of the same age. 

Finally, it is possible to run a real time simulation where offensive and defensive power ratings get updated along with players events: trades, injuries, etc.

Also, it is possible to run the entire season at once or multiple repetitions of a season to predict average performace of teams and players. 


## Brief technical description

There are 4 key elements of this simulation:

- 2 independent Neural Networks estimate team power rankings: One for Offense, one for Defense. Inputs are average of players projected stats (minutes-played-weighted). Output is the power which corresponds to points for or received against an average team.
- Simulation happens when the team powers are used as the estimated mean of a Normal distribution and a fixed common variance (based on empirical data in points variation across the league). This way, all the different probabilites associated with every event can be computed analytically, for instance, every team matchup. 
- Player similarity by age is computed using t-SNE algorithm which also allows for 2-D visualization of the data.
- Player stats are weighted by the amount of minutes played. Might seem like an obvious choice but, most of the time, stats are presented as totals or by game.  

## What can you simulate?

- Simulate an entire season, including playoffs (although the whole model is based on only regular season stats, adjustments can be made to simulate playoffs, for instance, increase the weights of the star players for each team by increasing the minutes they play)
- Run thousands of simulations to calculate probabilities of teams reaching playoffs, winning the championship, or number of wins. 
- Simulate trades between teams and calculate the change in offensive power and defensive power as a result of the trade. This allows teams to scan the market for the best possible replacement or direct acquisition of players in the market. Also allows ranking players by their offense and defense impact. 
- Explore data visually in 2D: 
    - Evolution of players
    - Geometric distribution of teams, find shapes or patterns that make a good/bad team
    - Understand how players cluster by their skills: richer structure than the classic 5 positions
    - Understand how NBA play has evolved over time. Example: the 3-point shooting
    
- Rank the players according to their Offensive and Defensive capabilities. Simulate players stats along with NBA scores during a season and find the perfect tune-in in minutes per game.

## Set up

To set up a new season there are a few data files that need updating. The key is to follow **read_data.R**

Outline of what needs to be updated

- Data for a new season:
    - Players stats up to last season: **write_playersHist.R**
    - Team stats up to last season: **write_TeamStats.R**
    - Franchises (there may be new franchises in the league)
    - Conferences (one day might change)
    - Season schedule

- Update Neural Network: Use **write_nnet.R** (load all data, load helper_functions and then run)
    
- Compute all the t-SNEs: list of t-SNE blocks. Use **write_tsneBlocks.R**

- Compute team powers:
    - Calculate playersNew: To update roster: transfers, injuries, playoffs, etc, use playersNew. At this level (playersNew) I can really affect the team's roster
    - Run **write_teams_power.R**:
        - .teamsPredictedPower(): Puts results of predicted powers in table
        - .computePower(): apply NNetwork model to input data
    - Run **neural_network.R**:
        - .prepareModelPrediction(): input for the NNetwork weighted average (minutes played) of playersNew.
    - Run **prepareRoster.R**:
        - .team_preparePredict(): Reads playersNew and calculates efficient stats.

## Data sources

Main data source is: https://www.basketball-reference.com/


## References

- Fivethirtyeight: Player similarity by age; https://fivethirtyeight.com/features/how-were-predicting-nba-player-career/
- Ayasdi: Data topology, the new positions in basketball: https://www.youtube.com/watch?v=E-gpSQQe3w8
- Andrew Gelman: model scores (something you can actually measure) not wins: http://andrewgelman.com/2014/02/25/basketball-stats-dont-model-probability-win-model-expected-score-differential/
- Neural Network package: R-blogger about NNet: https://www.r-bloggers.com/visualizing-neural-networks-in-r-update/
- tSNE algorithm: 
https://lvdmaaten.github.io/tsne/
- about interpretability of t-SNE:
http://distill.pub/2016/misread-tsne/

## Abstract

Title: Game of Trades: Simulating trade scenarios in the NBA

In this paper I present a method to evaluate the impact of player trades for NBA teams. Assesing the potential of trades is complex as it affects not only the composition of the teams involved but also the rest of the conference they play for. By acquiring a player, a team may strenghthen or weaken the opposing teams or themselves.

The main idea under this method is simulating the outcome of an entire NBA season under that trade scenario and compare it with the pre-trade outcome.

The starting point is a Neural Network regression model of Offensive and Defensive power for teams based on individual players stats which allows for simulation of head to head matches and thus for an entire season. By running multiple seasons under the same trade scenario it is possible to assess the average outcome for a team (per the Law of Large numbers) and the impact of each trade. 

The paper will show how Tthis model has implications beyond just the trade evaluation. For instance, by modeling the Offensive and Defensive power of teams, we will be able to answer questions like: Who won the Kyrie/Isaiah trade?; why the Spurs signed Pau Gasol to replace Tim Duncan?; who is the best/worst offensive/defensive player in the NBA?; who is Lonzo Ball's closest player?; and more.

In addition, the model allows for team success evaluation by using spatial or topological analysis to provide answers on what's the shape of a champion calibre team, in terms of positions of players in a multidimensional manifold.

*Note: At the writing of this paper, rosters are not yet final so I will be using rosters as of the end of last season 

Instructions:

Abstract submissions should be submitted online, and must adhere to the following guidelines:
See: [http://www.sloansportsconference.com/activities/research-papers/research-papers-competition-rules/]

- Abstracts must contain fewer than 500 words, including title and body.
- Abstracts may include up to two tables or figures combined (e.g. 1 figure and 1 table, or 2 tables)
- Each abstract should contain the following sections:
    - Introduction – What question is this research trying to answer? Why is it an important question for the industry?
    - Methods – Description of relevant statistical methods used, including data sources or data collection procedures
    - Results – Description of actual (not promised) results along with relevant statistics
    - Conclusion – The overall takeaway from the study, including how the results will impact the sports industry
- All abstracts must be submitted in one PDF through the 2018 Abstract Submission online submission page


Use the motivation as part of the intro. Key points to make: 

  - Why Spurs signed Gasol to replace Duncan?
  - How good/bad is the trade Isaiah - Kyrie for Celtics/Cavs?
  - How 3-point game has shaped the game and NBA champions in the last 5 years vs 20 years ago
  - What type of player will Lonzo Ball be? Who can he be compared to?
  - How close are Houston Rockets now to Golden State? What's the worst team in each conference?
  - Who are the best defensive/ofensive player in the league?
  - Classify players according to the way they play. What combination of these types does a team need to be a champion?
  - What type of player maximizes the winning chances of a team and who are the closest to that available in the market?

Provide some bits of data: compare CLE/BOS Offense and Defense before and after the trades. Simulate 1000 seasons to estimate their performances before and after the trade. 


