---
title: "NBA Player Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)

# variables set up
thisYear <- substr(Sys.Date(),1,4)
if (substr(Sys.Date(),6,7) > '08'){
  seasonOffset <- 0
} else {
  seasonOffset <- 1
}
thisSeason <- paste0(as.numeric(substr(Sys.Date(),1,4))-seasonOffset,"-",as.numeric(substr(Sys.Date(),1,4))-seasonOffset+1) 

# helper functions
files <- list.files("helper_functions", full.names = TRUE, recursive = TRUE)
for (f in files) source(f, local = TRUE)

# read data
team_stats <- read.csv("data/teamStats.csv") # from write_TeamStats.R
franchises <- read.csv("data/franchisesHistory.csv",stringsAsFactors = FALSE) 
team_stats <- merge(team_stats,franchises,by.x="Team",by.y="Franchise",all.x=TRUE)
#
playersHist <- read.csv("data/playersHist.csv", stringsAsFactors = FALSE) # from write_playersHist.R
playersHist <- .rename_PlayerDuplicates(playersHist) # differentiate players with the same name
playersPredictedStats_adjMin <- read.csv("data/playersNewPredicted_Final_adjMin.csv", stringsAsFactors = FALSE)
playersPredictedStats_adjPer <- read.csv("data/playersNewPredicted_Final_adjPer.csv", stringsAsFactors = FALSE)

# load neuralnet models
load("data/modelNeuralnet5_PTS.Rdata")
nn_Offense <- model$finalModel
load("data/modelNeuralnet5_PTSA.Rdata")
nn_Defense <- model$finalModel

# compute teams and players Offense and Defense
playersNewPredicted_Final_adjMinPer2 <- select(playersPredictedStats_adjPer, -contains("Per"), -effFG, -effFGA, -effPTS, -effTRB)
teamsPredicted <- .teamsPredictedPower(data = playersNewPredicted_Final_adjMinPer2,actualOrPred="predicted")
playersNewPredicted_OffDef <- mutate(playersNewPredicted_Final_adjMinPer2, Tm = Player, effMin = 1)
playersPredicted <- .teamsPredictedPower(data = playersNewPredicted_OffDef,actualOrPred="predicted") %>%
  mutate(Player = substr(team_season,1,regexpr("_",team_season)-1),plusMinus = TEAM_PTS-TEAM_PTSAG) %>%
  select(Player,Offense = TEAM_PTS, Defense = TEAM_PTSAG, plusMinus) %>%
  as.data.frame()
playersPredicted2 <- merge(playersPredicted,
                           playersPredictedStats_adjMin[,c("Player","Exp","Age","Tm","effMin")], by = "Player") %>%
  mutate(adjPlusMinus = plusMinus*effMin*100) %>%
  group_by(Tm) %>%
  mutate(teamPlusMinus = sum(adjPlusMinus,na.rm=TRUE)) %>%
  ungroup()

playerDashboard <- merge(playersPredictedStats_adjPer,select(playersPredicted2, -c(Age,Tm,effMin)), by = "Player")

playerRanks <- mutate_if(playerDashboard, is.numeric, function(x) row_number(desc(x)))

playerMax <- summarise_if(playerDashboard, is.numeric, max)
playerMin <- group_by(playerDashboard, Player) %>% summarise_if(is.numeric, min)

# tSNE for similiarity and historical evolution of players
tsne_ready_hist <- read.csv("data/tsne_ready_hist.csv", stringsAsFactors = FALSE)
# tSNE for predicted stats in new season
tsne_ready <- read.csv("data/tsne_ready_newSeason.csv", stringsAsFactors = FALSE)

```

Row {.sidebar}
-----------------------------------------------------------------------

```{r}
selectizeInput("playerName", "Select Player", choices = playerDashboard$Player, selected = playerDashboard$Player[1])

```


Row
-------------------------------------------------------------------------

### Offense {.value-box}
```{r}

vOff <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(Offense) %>% as.numeric()
  data
})

rOff <- reactive({
  data <- filter(playerRanks, Player == input$playerName) %>%
    select(Offense) %>% as.numeric()
  data
})

renderValueBox({
  
  valueBox(
    value = formatC(vOff(), digits = 1, format = "f"),
    caption = paste0("Offense (#",rOff(),")"),
    icon = "",
    color = ifelse(rOff() < nrow(playerRanks)/3,"green",ifelse(rOff() < nrow(playerRanks)*2/3,"lightblue","red"))
  )
})
```

### Defense {.value-box}
```{r}

vDef <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(Defense) %>% as.numeric()
  data
})

rDef <- reactive({
  data <- filter(playerRanks, Player == input$playerName) %>%
    mutate(Defense = nrow(playerRanks)-Defense) %>%
    select(Defense) %>% as.numeric()
  data
})

renderValueBox({
  
  valueBox(
    value = formatC(vDef(), digits = 1, format = "f"),
    caption = paste0("Defense (#",rDef(),")"),
    icon = "",
    color = ifelse(rDef() < nrow(playerRanks)/3,"green",ifelse(rDef() < nrow(playerRanks)*2/3,"lightblue","red"))
  )
})
```

### Usage Rate {.value-box}
```{r}

vMin <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(effMin) %>% as.numeric()
  data
})

rMin <- reactive({
  data <- filter(playerRanks, Player == input$playerName) %>%
    select(effMin) %>% as.numeric()
  data
})

renderValueBox({
  
  valueBox(
    value = paste0(formatC(vMin()*1000, digits = 1, format = "f"),"%"),
    caption = paste0("Usage (#",rMin(),")"),
    icon = "",
    color = ifelse(rMin() < nrow(playerRanks)/3,"green",ifelse(rMin() < nrow(playerRanks)*2/3,"lightblue","red"))
  )
})
```

### Experience {.value-box}
```{r}

vExp <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(Exp) %>% as.character()
  data
})

renderValueBox({
  
  valueBox(
    value = vExp(),
    icon = "",
    color = "lightgrey"
  )
})
```

### Age {.value-box}
```{r}

vAge <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(Age) %>% as.numeric()
  data
})

renderValueBox({
  
  valueBox(
    value = vAge(),
    icon = "",
    color = "lightgrey"
  )
})
```

### Team {.value-box}
```{r}

vTm <- reactive({
  data <- filter(playerDashboard, Player == input$playerName) %>%
    select(Tm) %>% as.character()
  data
})

renderValueBox({
  
  valueBox(
    value = vTm(),
    icon = "",
    color = "lightgrey"
  )
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Player Stats
```{r}
barplotPlayerStats <- reactive({
  
  off_def <- filter(playerDashboard, Player == input$playerName) %>% 
    select(Offense, Defense)
  #data <- filter(playerDashboard, Player == "LeBron James") %>% 
  data <- filter(playerDashboard, Player == input$playerName) %>% 
    select(contains("eff"), contains("Per")) %>%
    gather(Stat, Value) 
    #mutate(Value = ifelse(grepl("Per",Stat), paste0(round(Value*100,1),"%"),
    #                     ifelse(grepl("Min",Stat), paste0(round(Value*1000,1),"%"),round(Value,2))))
  
  ranks <- filter(playerRanks, Player == input$playerName) %>% 
  #ranks <- filter(playerRanks, Player == "LeBron James") %>% 
    select(contains("eff"), contains("Per")) %>%
    gather(Stat, Value) %>%
    mutate(color = ifelse(grepl("TOV|PF",Stat),
                          ifelse(Value > nrow(playerDashboard)/3,"green",
                                 ifelse(Value > nrow(playerDashboard)*2/3,"lightblue","red")),
                          ifelse(Value < nrow(playerDashboard)/3,"green",
                                 ifelse(Value < nrow(playerDashboard)*2/3,"lightblue","red")))) %>%
    mutate(Rank = Value) %>%
    select(-Value)
  
  data <- merge(data,ranks[,c("Stat","Rank","color")],by="Stat") %>% 
    mutate(order = c(8,7,11,10,15,20,17,5,4,2,14,13,23,18,22,1,19,21,16,6,9,3,12)) %>%
    mutate(Stat = as.factor(Stat)) %>%
    arrange(order)

  maxs <- select(playerMax, contains("eff"), contains("Per")) %>%
    gather(Stat, Value) %>%
    mutate(Stat = as.factor(Stat)) %>%
    merge(data[,c("Stat","order")],by="Stat") %>%
    arrange(order)

  data$Stat = factor(data$Stat, levels = data$Stat[order(data$order, decreasing = FALSE)], ordered=TRUE, 
                     labels = c("Points","effFG%","FG%","FG_A","FG_M","FG_2P%","FG_2PM","FG_2PA","FG_3P%","FG_3PM","FG_3PA","FT%","FT_M","FT_A","AST","TRB","DRB","ORB","STL","BLK","TOV","PF","Usage"))
  
  maxs$Stat = factor(maxs$Stat, levels = maxs$Stat[order(data$order, decreasing = FALSE)], ordered=TRUE, 
                     labels = c("Points","effFG%","FG%","FG_A","FG_M","FG_2P%","FG_2PM","FG_2PA","FG_3P%","FG_3PM","FG_3PA","FT%","FT_M","FT_A","AST","TRB","DRB","ORB","STL","BLK","TOV","PF","Usage"))
  
  ggplot(NULL) +
    geom_bar(data = data, aes(Stat, Value), stat = "identity", fill=factor(data$color)) +
    geom_bar(data = maxs, aes(Stat, Value), stat = "identity", fill = "grey", alpha = 0.3) +
    #coord_flip() +
    geom_text(data = data, aes(Stat,0.95,label = ifelse(grepl("%",Stat), paste0(round(Value*100,1),"%"),
                          ifelse(grepl("Usage",Stat), paste0(round(Value*1000,1),"%"),round(Value,2))))) +
    geom_text(data = data, aes(Stat,.85,label = paste0("(",Rank,")"))) +
    theme(legend.key=element_blank(),
              legend.title=element_blank(),
              legend.text = element_blank(),
              legend.position="none",
              plot.title = element_text(size=9),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.text.x = element_text(size = 8),
              #axis.text.y = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks = element_blank())
  
})

renderPlot(barplotPlayerStats())

```

### Similar Players 
```{r}

similar <- reactive({
  
  similarPlayers <- .compare10_click(thisSeason,input$playerName,data=tsne_ready) %>%
  #similarPlayers <- .compare10_click(thisSeason,"Kyrie Irving",data=tsne_ready) %>%
    top_n(11,-dist) %>% tail(10) %>% 
    merge(playerDashboard[,c("Player","Offense","Defense","effMin","Age","Tm")], by="Player") %>%
    mutate(Offense = round(Offense,1), Defense = round(Defense,1),dist = round(dist,2), effMin = paste0(formatC(effMin*1000,digits=1,format="f"),"%")) %>%
    arrange(dist) %>%
    select(Player,Team = Tm, Age, Offense, Defense, `Usage Rate` = effMin,`Euclidean dist` = dist)
    
  
  similarPlayers
})

renderTable(similar())  


```


### Similar Players Last 5 Seasons {data-width=350}
```{r}

similar_hist <- reactive({
  similarPlayers_Hist <- data.frame()
  player_seasons <- filter(tsne_ready_hist, Player == input$playerName) %>%
    arrange(desc(Season)) %>% select(Season) %>% head(5)
  for (s in player_seasons$Season) {
    thisSeason <- .compare10_click(s,input$playerName,data=tsne_ready_hist) %>%
      top_n(11,-dist) %>% tail(10) %>% mutate(player_season = paste0(Player," (",Season,")")) %>% select(player_season)
    names(thisSeason) <- c(paste0("In Season: ",s))
    if (nrow(similarPlayers_Hist) > 0) similarPlayers_Hist <- cbind(similarPlayers_Hist,thisSeason) else similarPlayers_Hist <- thisSeason
  }
  similarPlayers_Hist
})

renderTable(similar_hist())  


```

Row {.tabset .tabset-fade}
---------------------------------------------------

### Player t-SNE map 
```{r}
tsne_predicted <- reactive({
  
playerCluster <- kmeans(tsne_ready[, c("x","y")], 13, nstart = 10, iter.max = 20)
  tsne_ready2 <- cbind(tsne_ready, cluster = playerCluster$cluster)
  
  tsne_points_filter <- filter(tsne_ready2, Player == input$playerName)
    #centroid <- data.frame(x=(mean(tsne_points_filter$x)),y=mean(tsne_points_filter$y))
    x_limit <- c(min(tsne_points_filter$x)-5,max(tsne_points_filter$x)+10) 
    y_limit <- c(min(tsne_points_filter$y)-5,max(tsne_points_filter$y)+10)
  
  cluster_representative <- group_by(tsne_ready2, cluster) %>% 
    mutate(x_mean = mean(x), y_mean=mean(y)) %>%
    mutate(dist = sqrt((x-x_mean)^2+(y-y_mean)^2)) %>%
    filter(dist==min(dist)) %>%
    select(cluster, Player,Season, x,y,dist) %>%
    ungroup()
  
  if (nrow(tsne_points_filter) > 0) {   
    ggplot(NULL, aes(x,y)) +  
        geom_point(data=tsne_ready2,aes(color = as.factor(cluster)),alpha = 0.5) +
        geom_point(data=tsne_points_filter,color = "red",size=4) +
      geom_text(data = cluster_representative, aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
        geom_text(data=tsne_points_filter,aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
        theme(legend.key=element_blank(),
              legend.title=element_blank(),
              legend.text = element_blank(),
              legend.position="none",
              plot.title = element_text(size=9),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks = element_blank())
  } else {
    ggplot(NULL, aes(x,y)) +  
        geom_point(data=tsne_ready2,aes(color = as.factor(cluster)),alpha = 0.5) +
      geom_text(data = cluster_representative, aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
        theme(legend.key=element_blank(),
              legend.title=element_blank(),
              legend.text = element_blank(),
              legend.position="none",
              plot.title = element_text(size=9),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks = element_blank())
  }

})

renderPlot(tsne_predicted())
```

### t-SNE timeline
```{r}

tsne_historical <- reactive({
  
  playerCluster <- kmeans(tsne_ready_hist[, c("x","y")], 13, nstart = 10, iter.max = 20)
  tsne_ready_hist2 <- cbind(tsne_ready_hist, cluster = playerCluster$cluster)
  
  tsne_points_filter <- filter(tsne_ready_hist2, Player == input$playerName)
    #centroid <- data.frame(x=(mean(tsne_points_filter$x)),y=mean(tsne_points_filter$y))
    x_limit <- c(min(tsne_points_filter$x)-5,max(tsne_points_filter$x)+10) 
    y_limit <- c(min(tsne_points_filter$y)-5,max(tsne_points_filter$y)+10)
  
  cluster_representative <- group_by(tsne_ready_hist2, cluster) %>% 
    mutate(x_mean = mean(x), y_mean=mean(y)) %>%
    mutate(dist = sqrt((x-x_mean)^2+(y-y_mean)^2)) %>%
    filter(dist==min(dist)) %>%
    select(cluster, Player,Season, x,y,dist) %>%
    ungroup()
  
  if (nrow(tsne_points_filter) > 0) {   
    ggplot(NULL, aes(x,y)) +  
        geom_point(data=tsne_ready_hist2,aes(color = as.factor(cluster)),alpha = 0.2) +
        geom_point(data=tsne_points_filter,color = "red",size=4) +
        geom_text(data = cluster_representative, aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
        geom_text(data=tsne_points_filter,aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
        theme(legend.key=element_blank(),
              legend.title=element_blank(),
              legend.text = element_blank(),
              legend.position="none",
              plot.title = element_text(size=9),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks = element_blank())
  } else {
    ggplot(NULL, aes(x,y)) +  
      geom_point(data=tsne_ready_hist2,aes(color = as.factor(cluster)),alpha = 0.2) +
      geom_text(data = cluster_representative, aes(label = paste0(Player," (",Season,")")),size=3, nudge_y = 1) +
      theme(legend.key=element_blank(),
              legend.title=element_blank(),
              legend.text = element_blank(),
              legend.position="none",
              plot.title = element_text(size=9),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks = element_blank())
  }
})

renderPlot(tsne_historical())

```





